services:
  node:
    image: ghcr.io/mcarr823/opnsense-update-check:amd64
    #image: ghcr.io/mcarr823/opnsense-update-check:arm64
    environment:
      VERIFY: 'false'
      KEY: ''
      SECRET: ''
      HOST: ''
      EMAIL: ''
      NAME: ''
      SENDER: ''
      SMTP_HOST: ''
      SMTP_PORT: 25
      SMTP_USER: ''
      SMTP_PASS: ''
      ALERT_NO_UPDATES: 'true'